# .github/workflows/chromatic.yml

# name of our action
name: 'Chromatic'
# the event that will trigger the action
on: push

# what the action will do
jobs:
    test:
        # the operating system it will run on
        runs-on: ubuntu-latest
        # the list of steps that the action will go through
        steps:
            - uses: actions/checkout@v1 # checkout, update to latest version
            - run: yarn
            - uses: chromaui/action@v1 # push to chromatic
              # options required for the GitHub chromatic action
              with:
                  projectToken: project-token
                  token: #{{ secrets.GITHUB_TOKEN }}
